In [4]:
# ===================================================
# Raw data : SCHARE_GHI_Global_Horizontal_Irradiance_1991_2012
# Purpose Agreegating GHI Data.    
# File Creator : Neha Khairnar
# ==================================================
# 📦 Step 1: Imports
# =========================
import pandas as pd
from pathlib import Path

# =========================
# 📂 Step 2: Load Data
# =========================
BASE_DIR = Path().resolve().parent
#DATA_PATH = BASE_DIR / "data" / "dataset" / "ghi.csv"
#df = pd.read_csv(DATA_PATH)

#df = pd.read_csv("../data/Datasets/SCHARE_GHI_Global_Horizontal_Irradiance_1991_2012/Population-Weighted_Global_Horizontal_Irradiance__1991-2012.csv", nrows=100)
df = pd.read_csv("../data/Datasets/SCHARE_GHI_Global_Horizontal_Irradiance_1991_2012/Population-Weighted_Global_Horizontal_Irradiance__1991-2012.csv")

print("Raw Data Preview:")
display(df.head(10))


# =========================
# 🧹 Step 3: Rename Columns
# =========================
df.columns = [
    "statefips",
    "countyfips",
    "year",
    "month",
    "day",
    "ghi"
]


# =========================
# 📅 Step 4: Create Date
# =========================
df["date"] = pd.to_datetime(df[["year", "month", "day"]])

# =========================
# 🧱 Step 5: Fix FIPS (IMPORTANT FIX)
# =========================
# State FIPS → 2 digits
df["state_fips"] = df["statefips"].astype(str).str.zfill(2)

# County FIPS (already combined like 1001)
#df["countyfips"] = df["countyfips"].astype(str).str.zfill(5)

# Extract last 3 digits for county
#df["county_fips"] = df["countyfips"].str[-3:]
df["county_fips"] = df["countyfips"].astype(str).str.zfill(5).str[-3:]

# =========================
# 🧾 Step 6: Clean Dataset
# =========================
ghi_clean = df[
    [
        "year",
        "date",
        "state_fips",
        "county_fips",
        "ghi"
    ]
]

print("Cleaned Daily GHI:")
display(ghi_clean.head(10))

# ======================================================================
# 💾 Step 8: Save Clean Dataset
# =======================================================================

OUTPUT_PATH = BASE_DIR / "data" / "processed" / "neighbourhood_ghi_clean.csv"

# Create folder if not exists
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
ghi_clean.to_csv(OUTPUT_PATH, index=False)
print(f"\n✅ File saved to: {OUTPUT_PATH}")

# =========================
# 📊 Step 9: Yearly Aggregation
# =========================
ghi_yearly = (
    ghi_clean.groupby(["year", "state_fips", "county_fips"])
    .agg(
        GHI_mean=("ghi", "mean")
    )
    .reset_index()
)

# =========================
# 👀 Step 8: Preview
# =========================
print("Yearly GHI:")
display(ghi_yearly.head(10))


# =========================
# 📊 Step 9: Validate
# =========================
print("Shape:", ghi_yearly.shape)
print(ghi_yearly.info())

# =========================
# 💾 Step 10: Save
# =========================
OUTPUT_PATH = BASE_DIR / "data" / "processed" / "neighbourhood_ghi_yearly.csv"

OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

ghi_yearly.to_csv(OUTPUT_PATH, index=False)

print("Saved to:", OUTPUT_PATH)

Raw Data Preview:

   statefips  countyfips  year  month  day          ghi
0          1        1001  1991      1    1  1442.806820
1          1        1001  1991      1    2  1416.738234
2          1        1001  1991      1    3  1143.938697
3          1        1001  1991      1    4  1148.309969
4          1        1001  1991      1    5  1293.868578
5          1        1001  1991      1    6  1322.174994
6          1        1001  1991      1    7  1353.693030
7          1        1001  1991      1    8  1003.112816
8          1        1001  1991      1    9  1278.118321
9          1        1001  1991      1   10  1097.093700

Cleaned Daily GHI:

   year       date state_fips county_fips          ghi
0  1991 1991-01-01         01         001  1442.806820
1  1991 1991-01-02         01         001  1416.738234
2  1991 1991-01-03         01         001  1143.938697
3  1991 1991-01-04         01         001  1148.309969
4  1991 1991-01-05         01         001  1293.868578
5  1991 1991-01-06         01         001  1322.174994
6  1991 1991-01-07         01         001  1353.693030
7  1991 1991-01-08         01         001  1003.112816
8  1991 1991-01-09         01         001  1278.118321
9  1991 1991-01-10         01         001  1097.093700

✅ File saved to: C:\Users\NVK00\Desktop\MyData\Projects\Clinical_Neighbourhood_ML_Data_Predictor\data\processed\neighbourhood_ghi_clean.csv
Yearly GHI:

   year state_fips county_fips     GHI_mean
0  1991         01         001  4212.321823
1  1991         01         003  4338.761438
2  1991         01         005  4221.844413
3  1991         01         007  4214.792647
4  1991         01         009  4117.891131
5  1991         01         011  4200.225322
6  1991         01         013  4251.243963
7  1991         01         015  4113.680532
8  1991         01         017  4138.015299
9  1991         01         019  4085.536463

Shape: (68398, 4)
<class 'pandas.DataFrame'>
RangeIndex: 68398 entries, 0 to 68397
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         68398 non-null  int64
 1   state_fips   68398 non-null  str
 2   county_fips  68398 non-null  str
 3   GHI_mean     68398 non-null  float64
dtypes: float64(1), int64(1), str(2)
memory usage: 2.1 MB
None
Saved to: C:\Users\NVK00\Desktop\MyData\Projects\Clinical_Neighbourhood_ML_Data_Predictor\data\processed\neighbourhood_ghi_yearly.csv